# Generated by Django 6.0.1 on 2026-01-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeface'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeface',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
