# Generated by Django 6.0.1 on 2026-01-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='delay_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('on_time', 'A tiempo'), ('late', 'Atraso'), ('early_leave', 'Salida temprana'), ('overtime', 'Hora extra'), ('unknown', 'Sin regla')], default='unknown', max_length=20),
        ),
    ]
