# Generated by Django 6.0.1 on 2026-01-18 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_delay_minutes_attendance_scheduled_time_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.TimeField(default='08:00')),
                ('exit_time', models.TimeField(default='17:00')),
                ('grace_minutes', models.PositiveIntegerField(default=5)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policy', to='core.company')),
            ],
        ),
    ]
